# Generated by Django 6.0 on 2025-12-20 19:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número do Pedido')),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Cliente')),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('delivery_address', models.TextField(blank=True, null=True, verbose_name='Endereço de Entrega')),
                ('is_delivery', models.BooleanField(default=False, verbose_name='É entrega?')),
                ('status', models.CharField(choices=[('open', '🟡 Aberto'), ('preparing', '👨\u200d🍳 Em preparo'), ('ready', '✅ Pronto para entrega'), ('out_for_delivery', '🚗 Saiu para entrega'), ('delivered', '📦 Entregue'), ('cancelled', '❌ Cancelado')], default='open', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgente'), ('priority', 'Prioritário')], default='normal', max_length=20, verbose_name='Prioridade')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('estimated_time', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(180)], verbose_name='Tempo Estimado (min)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('prepared_at', models.DateTimeField(blank=True, null=True, verbose_name='Preparado em')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregue em')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Subtotal')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Taxa de Entrega')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Desconto')),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Impostos')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total')),
                ('payment_method', models.CharField(choices=[('cash', 'Dinheiro'), ('credit_card', 'Cartão de Crédito'), ('debit_card', 'Cartão de Débito'), ('pix', 'PIX'), ('online', 'Online')], default='cash', max_length=20, verbose_name='Método de Pagamento')),
                ('payment_status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='Status do Pagamento')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='orders_orde_status_25e057_idx'), models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'), models.Index(fields=['customer_phone'], name='orders_orde_custome_59f5e1_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('special_instructions', models.TextField(blank=True, null=True, verbose_name='Instruções Especiais')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItemCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=50, verbose_name='Opção')),
                ('choice', models.CharField(max_length=50, verbose_name='Escolha')),
                ('extra_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço Extra')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customizations', to='orders.orderitem')),
            ],
            options={
                'verbose_name': 'Customização',
                'verbose_name_plural': 'Customizações',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_by', models.CharField(max_length=100)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'verbose_name': 'Histórico de Status',
                'verbose_name_plural': 'Históricos de Status',
                'ordering': ['-changed_at'],
            },
        ),
    ]
