# Generated by Django 6.0 on 2025-12-20 19:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome da Tag')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('color', models.CharField(default='#007bff', help_text='Cor em hexadecimal (ex: #007bff)', max_length=7, verbose_name='Cor da Tag')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome da Categoria')),
                ('slug', models.SlugField(help_text='Identificador único para URLs', max_length=60, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordem de exibição (menor aparece primeiro)', verbose_name='Ordem')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('show_in_menu', models.BooleanField(default=True, verbose_name='Mostrar no menu')),
                ('icon', models.CharField(blank=True, help_text='Código do ícone (ex: fas fa-hamburger)', max_length=50, null=True, verbose_name='Ícone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['slug', 'active'], name='products_pr_slug_220e5d_idx'), models.Index(fields=['order'], name='products_pr_order_209961_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Código único do produto', max_length=50, unique=True, verbose_name='SKU')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Produto')),
                ('slug', models.SlugField(max_length=110, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição Detalhada')),
                ('short_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição Curta')),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='Custo de produção/aquisição', max_digits=10, verbose_name='Preço de Custo')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda')),
                ('promotional_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Promocional')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('out_of_stock', 'Sem estoque'), ('coming_soon', 'Em breve')], default='active', max_length=20, verbose_name='Status')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo para venda')),
                ('featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem no Menu')),
                ('manage_stock', models.BooleanField(default=False, verbose_name='Controlar Estoque')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('low_stock_threshold', models.IntegerField(default=0, verbose_name='Limite de Estoque Baixo')),
                ('calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='Calorias (kcal)')),
                ('preparation_time', models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='Tempo de Preparo (min)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagem Principal')),
                ('additional_images', models.JSONField(blank=True, help_text='Lista de URLs de imagens extras', null=True, verbose_name='Imagens Adicionais')),
                ('allow_customizations', models.BooleanField(default=False, verbose_name='Permitir Customizações')),
                ('max_customizations', models.PositiveIntegerField(default=3, verbose_name='Máximo de Customizações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productcategory', verbose_name='Categoria')),
                ('tags', models.ManyToManyField(blank=True, to='products.producttag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCustomizationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Opção')),
                ('type', models.CharField(choices=[('checkbox', 'Checkbox (Sim/Não)'), ('select', 'Seleção Única'), ('multiple', 'Seleção Múltipla'), ('number', 'Quantidade')], default='checkbox', max_length=20)),
                ('required', models.BooleanField(default=False, verbose_name='Obrigatório')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customization_options', to='products.product')),
            ],
            options={
                'verbose_name': 'Opção de Customização',
                'verbose_name_plural': 'Opções de Customização',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Promoção')),
                ('slug', models.SlugField(max_length=110, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('promotion_type', models.CharField(choices=[('percentage', 'Percentual'), ('fixed', 'Valor Fixo'), ('bundle', 'Combo')], default='percentage', max_length=20, verbose_name='Tipo de Promoção')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentual ou valor fixo', max_digits=10, verbose_name='Valor do Desconto')),
                ('start_date', models.DateTimeField(verbose_name='Data de Início')),
                ('end_date', models.DateTimeField(verbose_name='Data de Término')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Promoções com maior prioridade têm precedência', verbose_name='Prioridade')),
                ('minimum_order_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Mínimo do Pedido')),
                ('maximum_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Desconto Máximo')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Limite de Usos')),
                ('times_used', models.PositiveIntegerField(default=0, editable=False, verbose_name='Vezes Usada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='promotions', to='products.productcategory', verbose_name='Categorias Incluídas')),
                ('products', models.ManyToManyField(blank=True, related_name='promotions', to='products.product', verbose_name='Produtos Incluídos')),
            ],
            options={
                'verbose_name': 'Promoção',
                'verbose_name_plural': 'Promoções',
                'ordering': ['-priority', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Entrada'), ('out', 'Saída'), ('adjustment', 'Ajuste'), ('return', 'Devolução')], max_length=20)),
                ('quantity', models.IntegerField(verbose_name='Quantidade')),
                ('previous_quantity', models.IntegerField(verbose_name='Quantidade Anterior')),
                ('new_quantity', models.IntegerField(verbose_name='Nova Quantidade')),
                ('reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='Motivo')),
                ('reference', models.CharField(blank=True, help_text='Número do pedido, nota fiscal, etc.', max_length=100, null=True, verbose_name='Referência')),
                ('created_by', models.CharField(max_length=100, verbose_name='Registrado por')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.product')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCustomizationChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Escolha')),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Modificador de Preço')),
                ('available', models.BooleanField(default=True, verbose_name='Disponível')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='products.productcustomizationoption')),
            ],
            options={
                'verbose_name': 'Escolha de Customização',
                'verbose_name_plural': 'Escolhas de Customização',
                'ordering': ['order', 'name'],
                'unique_together': {('option', 'name')},
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='products_pr_sku_ca0cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'active'], name='products_pr_categor_24b98b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['featured'], name='products_pr_feature_55f52f_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['active', 'start_date', 'end_date'], name='products_pr_active_4b7dc0_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', 'created_at'], name='products_st_product_a806c1_idx'),
        ),
    ]
